import { useEffect, useState } from "react";
import type { BlueprintProposal, ProviderCatalog, ProviderSelection, ProviderStatus as ProviderStatusData } from "@the-vault/shared";
import { api } from "../lib/api";
import { BlueprintProposal as BlueprintProposalCard } from "./BlueprintProposal";
import { ProviderStatus } from "./ProviderStatus";
import { ProviderRoleControl } from "./ProviderRoleControl";

export function BriefComposer({ providerStatus, catalog, catalogLoading, onRefreshCatalog, onApprove, onManual, onCancel }: { providerStatus?: ProviderStatusData; catalog?: ProviderCatalog; catalogLoading: boolean; onRefreshCatalog: () => Promise<boolean>; onApprove: (proposal: BlueprintProposal) => Promise<void>; onManual: () => void; onCancel: () => void }) {
  const [brief, setBrief] = useState("Build a responsive analytics dashboard panel for an internal product. It should load data from an existing API, show loading/error/empty/ready states, support keyboard navigation, and keep server persistence outside the component.");
  const defaultSelection: ProviderSelection = catalog?.configured.analysis ?? (providerStatus?.configured.name === "ollama" ? { provider: "ollama", model: providerStatus.models?.analysis ?? providerStatus.configured.model } : { provider: "mock", model: "deterministic-local" });
  const [analysisSelection, setAnalysisSelection] = useState<ProviderSelection>(defaultSelection);
  const [proposal, setProposal] = useState<BlueprintProposal>();
  const [generating, setGenerating] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  useEffect(() => { if (catalog && analysisSelection.provider === "ollama" && !analysisSelection.model) setAnalysisSelection(catalog.configured.analysis); }, [catalog, analysisSelection.model, analysisSelection.provider]);
  const selectedOption = catalog?.models.find((option) => option.provider === analysisSelection.provider && option.model === analysisSelection.model);
  const selectionUnavailable = analysisSelection.provider === "ollama" && (!selectedOption || !selectedOption.available);
  async function generate(event: React.FormEvent) { event.preventDefault(); if (selectionUnavailable) return; setGenerating(true); setError(""); try { setProposal(await api.generateBlueprintProposal(brief, analysisSelection.provider === "mock" ? "mock" : "configured", analysisSelection)); } catch (generationError) { setError(generationError instanceof Error ? generationError.message : "Unable to generate proposal"); } finally { setGenerating(false); } }
  async function approve() { if (!proposal) return; setSaving(true); try { await onApprove(proposal); } finally { setSaving(false); } }
  if (proposal) return <BlueprintProposalCard proposal={proposal} saving={saving} onApprove={approve} onEdit={() => setProposal(undefined)} />;
  return <section className="composer-grid">
    <div className="panel composer-hero"><div className="orb orb-one" /><div className="orb orb-two" /><div className="relative"><div className="flex items-center justify-between gap-4"><div><p className="eyebrow">Local intelligence</p><h2 className="section-title text-2xl">Start with intent.</h2></div><ProviderStatus status={providerStatus} catalog={catalog} /></div><p className="mt-4 max-w-xl text-sm leading-7 text-slate-300">Describe the outcome in your own language. The local model will turn it into a structured blueprint and a bounded implementation packet for your review.</p><form className="mt-6" onSubmit={generate}><label className="field"><span>What are you building?</span><textarea className="brief-input" rows={8} value={brief} onChange={(event) => setBrief(event.target.value)} placeholder="Describe the feature, its users, its boundaries, and what success looks like…" /></label>{error && <div className="alert-error mt-4">{error}</div>}<div className="mt-5 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><ProviderRoleControl role="analysis" catalog={catalog} loading={catalogLoading} selection={analysisSelection} onChange={setAnalysisSelection} onRefresh={onRefreshCatalog} /><button className="button-primary" disabled={generating || !brief.trim() || selectionUnavailable} type="submit">{generating ? <><span className="inline-spinner" /> Thinking locally…</> : "Generate blueprint →"}</button></div></form><div className="mt-6 flex flex-wrap gap-2 text-xs text-slate-500"><span className="signal-pill">Schema validated</span><span className="signal-pill">Cloud models hidden</span><span className="signal-pill">Human approval required</span></div></div></div>
    <div className="panel composer-side"><p className="eyebrow">How the handoff works</p><div className="flow-list"><div className="flow-item"><span className="flow-number">01</span><div><strong>Describe</strong><p>Your brief stays the source of intent.</p></div></div><div className="flow-item"><span className="flow-number">02</span><div><strong>Shape</strong><p>Ollama proposes fields, constraints, and checks.</p></div></div><div className="flow-item"><span className="flow-number">03</span><div><strong>Review</strong><p>You approve the packet before execution.</p></div></div></div><div className="side-callout"><span className="text-xl text-cyan-200">✦</span><p>AI proposes. The architecture remains yours.</p></div></div>
    <div className="col-span-full flex flex-col-reverse justify-end gap-3 sm:flex-row"><button className="button-secondary" type="button" onClick={onCancel}>Cancel</button><button className="button-secondary" type="button" onClick={onManual}>Use structured form instead</button></div>
  </section>;
}
