import type { ExecutionRecord } from "@the-vault/shared";
import type { ExecutionDetails } from "../lib/api";

const labels: Record<ExecutionRecord["status"], string> = { pending: "Pending", running: "Running", completed: "Completed", failed: "Failed", "needs-review": "Needs review" };

export function ExecutionResult({ execution }: { execution?: ExecutionDetails }) {
  if (!execution) return <div className="empty-panel"><span className="step-icon">03</span><div><h3 className="font-semibold text-white">No execution result yet</h3><p className="mt-1 text-sm text-slate-400">Launch the approved prompt to create an evidence-backed result.</p></div></div>;
  return <section className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-white/10 px-5 py-4"><div><p className="eyebrow">Execution result</p><h2 className="section-title">Provider response</h2></div><span className={`status status-${execution.status}`}>{labels[execution.status]}</span></div><div className="grid gap-4 p-5 sm:grid-cols-3"><div><p className="meta-label">Provider</p><p className="meta-value">{execution.artifactType || "Pending"}</p></div><div><p className="meta-label">Started</p><p className="meta-value">{execution.startedAt ? new Date(execution.startedAt).toLocaleTimeString() : "—"}</p></div><div><p className="meta-label">Artifact</p><p className="meta-value truncate">{execution.artifactLocation || "Not created"}</p></div></div>{execution.generatedOutput ? <pre className="max-h-[360px] overflow-auto whitespace-pre-wrap border-t border-white/10 p-5 font-mono text-xs leading-6 text-slate-300">{execution.generatedOutput}</pre> : <p className="border-t border-white/10 p-5 text-sm text-slate-400">{execution.status === "failed" ? execution.verificationNotes : "The provider has not returned an artifact yet."}</p>}</section>;
}
