import type { ExecutionRecord } from "@the-vault/shared";
import type { ExecutionDetails } from "../lib/api";
import { CopyMarkdownButton } from "./CopyMarkdownButton";
import type { CoreDocumentFilename } from "@the-vault/shared";
import { DocumentSelectGrid } from "./DocumentSelectGrid";
import { MarkdownPreview } from "./MarkdownPreview";

const labels: Record<ExecutionRecord["status"], string> = { pending: "Pending", running: "Running", completed: "Completed", failed: "Failed", "needs-review": "Needs review" };

export function ExecutionResult({ execution, onGenerateCoreDocs, generatingCoreDocs, selectedCoreDocs, onCoreDocsChange }: { execution?: ExecutionDetails; onGenerateCoreDocs?: () => void; generatingCoreDocs?: boolean; selectedCoreDocs?: CoreDocumentFilename[]; onCoreDocsChange?: (files: CoreDocumentFilename[]) => void }) {
  if (!execution) return <div className="empty-panel"><span className="step-icon">03</span><div><h3 className="font-semibold text-white">No execution result yet</h3><p className="mt-1 text-sm text-slate-400">Launch the approved prompt to create an evidence-backed result.</p></div></div>;

  const isPrd = execution.artifactType === "PRD";

  return <section className="panel overflow-hidden"><div className="flex items-center justify-between gap-4 border-b border-white/10 px-5 py-4"><div><p className="eyebrow">04 · Execution result</p><h2 className="section-title">Provider response</h2></div><div className="flex items-center gap-3"><CopyMarkdownButton markdown={execution.generatedOutput} disabled={!execution.generatedOutput} /><span className={`status status-${execution.status}`}>{labels[execution.status]}</span></div></div><div className="grid gap-4 p-5 sm:grid-cols-4"><div><p className="meta-label">Provider</p><p className="meta-value">{(execution.provider?.name ?? execution.artifactType) || "Pending"}{execution.provider?.model ? <span className="block text-xs text-slate-500">{execution.provider.model}</span> : null}</p></div><div><p className="meta-label">Duration</p><p className="meta-value">{execution.provider?.durationMs ? `${execution.provider.durationMs}ms` : "—"}</p></div><div><p className="meta-label">Started</p><p className="meta-value">{execution.startedAt ? new Date(execution.startedAt).toLocaleTimeString() : "—"}</p></div><div><p className="meta-label">Artifact</p><p className="meta-value truncate">{execution.artifactLocation || "Not created"}</p></div></div>{execution.provider?.fallback && <div className="border-t border-amber-300/20 bg-amber-300/[.06] px-5 py-3 text-xs text-amber-100">Explicit fallback used: {execution.provider.message ?? "deterministic local provider"}</div>}{execution.generatedOutput ? <><div className="max-h-[480px] overflow-auto border-t border-white/10 p-5">{isPrd ? <MarkdownPreview markdown={execution.generatedOutput} /> : <pre className="whitespace-pre-wrap font-mono text-xs leading-6 text-slate-300">{execution.generatedOutput}</pre>}</div>{execution.status === "completed" && isPrd && onGenerateCoreDocs && selectedCoreDocs && onCoreDocsChange && <div className="space-y-5 border-t border-white/10 p-5"><DocumentSelectGrid selected={selectedCoreDocs} onChange={onCoreDocsChange} /><div className="flex justify-end"><button className="button-primary" disabled={generatingCoreDocs || selectedCoreDocs.length === 0} onClick={onGenerateCoreDocs}>{generatingCoreDocs ? <><span className="inline-spinner" /> Opening workspace…</> : "Generate Core Documentation →"}</button></div></div>}</> : <p className="border-t border-white/10 p-5 text-sm text-slate-400">{execution.status === "failed" ? execution.verificationNotes : "The provider has not returned an artifact yet."}</p>}</section>;
}
