import { useEffect, useState } from "react";
import type { Blueprint, CoreDocumentFilename, ExecutionRecord, PromptArtifact, ProviderCatalog, ProviderSelection } from "@the-vault/shared";
import { api } from "../lib/api";
import type { ExecutionDetails } from "../lib/api";
import { ExecutionTimeline } from "../components/ExecutionTimeline";
import { PromptPreview } from "../components/PromptPreview";
import { ExecutionLauncher } from "../components/ExecutionLauncher";
import { ExecutionResult } from "../components/ExecutionResult";
import { VerificationPanel } from "../components/VerificationPanel";
import { createVaultPacket, downloadVaultPacket } from "../lib/packet-export";

function StageRail({ blueprint, prompt, execution }: { blueprint: Blueprint; prompt?: PromptArtifact; execution?: ExecutionDetails }) {
  const stages = [
    { label: "Blueprint", detail: blueprint.source === "ollama" ? "AI proposal approved" : "Human intent captured", complete: true },
    { label: "Prepare", detail: prompt ? "Prompt artifact ready" : "Compile context", complete: Boolean(prompt) },
    { label: "Execute", detail: execution?.status === "completed" ? "Artifact generated" : "Run controlled provider", complete: execution?.status === "completed" },
    { label: "Verify", detail: execution?.verificationNotes ? "Evidence recorded" : "Add human evidence", complete: Boolean(execution?.verificationNotes) }
  ];
  return <div className="stage-rail">{stages.map((stage, index) => <div className={`stage-item ${stage.complete ? "stage-complete" : ""}`} key={stage.label}><div className="stage-marker">{stage.complete ? "✓" : String(index + 1).padStart(2, "0")}</div><div><p>{stage.label}</p><span>{stage.detail}</span></div>{index < stages.length - 1 && <div className="stage-line" />}</div>)}</div>;
}

export function BlueprintDetail({ id, catalog, catalogLoading, onRefreshCatalog, onNavigate }: { id: string; catalog?: ProviderCatalog; catalogLoading: boolean; onRefreshCatalog: () => Promise<boolean>; onNavigate: (path: string) => void }) {
  const [blueprint, setBlueprint] = useState<Blueprint>(); const [prompt, setPrompt] = useState<PromptArtifact>(); const [executions, setExecutions] = useState<ExecutionRecord[]>([]); const [execution, setExecution] = useState<ExecutionDetails>(); const [loading, setLoading] = useState(true); const [generating, setGenerating] = useState(false); const [launching, setLaunching] = useState(false); const [verifying, setVerifying] = useState(false); const [exported, setExported] = useState(false); const [error, setError] = useState(""); const [errorAction, setErrorAction] = useState<"compile" | "launch" | "verify" | "export" | "load">("load");
  const [generatingCoreDocs, setGeneratingCoreDocs] = useState(false); const [selectedCoreDocs, setSelectedCoreDocs] = useState<CoreDocumentFilename[]>(["ARCHITECTURE.md", "API.md", "DEPLOYMENT.md", "TROUBLESHOOTING.md"]);
  async function load() { try { const [nextBlueprint, nextExecutions] = await Promise.all([api.getBlueprint(id), api.getExecutions(id)]); setBlueprint(nextBlueprint); setExecutions(nextExecutions); if (nextExecutions[0]) setExecution(await api.getExecution(nextExecutions[0].id)); try { setPrompt(await api.getPrompt(id)); } catch (promptError) { if (!(promptError instanceof Error && promptError.message === "Prompt artifact not found")) throw promptError; } } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Unable to load blueprint"); setErrorAction("load"); } finally { setLoading(false); } }
  const [creationSelection, setCreationSelection] = useState<ProviderSelection>();
  useEffect(() => { setCreationSelection(undefined); void load(); }, [id]);
  useEffect(() => { if (!creationSelection && blueprint && (blueprint.source === "mock" || catalog)) setCreationSelection(blueprint.source === "mock" ? { provider: "mock", model: "deterministic-local" } : catalog?.configured.creation ?? { provider: "mock", model: "deterministic-local" }); }, [blueprint, catalog, creationSelection]);
  async function generate() { setGenerating(true); setError(""); setErrorAction("compile"); try { const result = await api.generatePrompt(id); setPrompt(result.promptArtifact); setExecutions((current) => [result.executionRecord, ...current]); setExecution(undefined); } catch (generateError) { setError(`We couldn't compile this prompt. ${generateError instanceof Error ? generateError.message : "Please try again."}`); } finally { setGenerating(false); } }
  async function launch() { if (!prompt || !creationSelection) return; setLaunching(true); setError(""); setErrorAction("launch"); try { const result = await api.launchExecution(prompt.id, creationSelection.provider === "mock" ? "mock" : "configured", creationSelection); setExecution(result); setExecutions((current) => [result, ...current.filter((item) => item.id !== result.id)]); } catch (launchError) { setError(`Execution could not start. ${launchError instanceof Error ? launchError.message : "Please try again."}`); } finally { setLaunching(false); } }
  async function verify(notes: string) { if (!execution) return; setVerifying(true); setError(""); setErrorAction("verify"); try { const result = await api.verifyExecution(execution.id, notes); setExecution(result); setExecutions((current) => current.map((item) => item.id === result.id ? result : item)); } catch (verifyError) { setError(`We couldn't save the verification note. ${verifyError instanceof Error ? verifyError.message : "Please try again."}`); } finally { setVerifying(false); } }
  function handleGenerateCoreDocs() {
    if (!blueprint || !creationSelection || selectedCoreDocs.length === 0) return;
    const requestedFiles = ["README.md", ...selectedCoreDocs];
    const params = new URLSearchParams({ requestedFiles: requestedFiles.join(","), provider: creationSelection.provider, model: creationSelection.model ?? "" });
    setGeneratingCoreDocs(true);
    setError("");
    setErrorAction("launch");
    onNavigate(`/blueprints/${blueprint.id}/workspace?${params.toString()}`);
  }
  function exportPacket() { if (!blueprint) return; setError(""); try { downloadVaultPacket(createVaultPacket({ blueprint, prompt, executions, selectedExecution: execution })); setExported(true); window.setTimeout(() => setExported(false), 1800); } catch (exportError) { setError(`We couldn't export this packet. ${exportError instanceof Error ? exportError.message : "Please try again."}`); setErrorAction("export"); } }
  if (loading) return <div className="empty-panel"><div className="spinner" /><p>Loading blueprint…</p></div>;
  if (!blueprint) return <div className="alert-error">{error || "Blueprint not found"}</div>;
  return <>
    <div className="mb-8"><button className="back-link" onClick={() => onNavigate("/dashboard")}>← Back to vault</button><div className="mt-8 flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><div className="flex flex-wrap items-center gap-3"><span className="tag">{blueprint.framework}</span><span className="source-chip">{blueprint.source === "ollama" ? "Generated with Ollama" : blueprint.source === "mock" ? "Mock proposal" : "Human authored"}</span><span className="text-xs text-slate-500">Updated {new Date(blueprint.updatedAt).toLocaleDateString()}</span></div><h1 className="page-title mt-4">{blueprint.name}</h1><p className="page-subtitle">{blueprint.description}</p></div><div className="flex flex-col gap-3 sm:flex-row"><button className="button-secondary" type="button" onClick={exportPacket}>{exported ? "Exported" : "Export Packet"}</button><button className="button-primary" disabled={generating} onClick={() => void generate()}>{generating ? "Compiling…" : prompt ? "Regenerate prompt →" : "Compile prompt →"}</button></div></div></div>
    <StageRail blueprint={blueprint} prompt={prompt} execution={execution} />
    {error && <div className="alert-error mb-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between" role="alert" aria-live="assertive"><div><strong className="block">{errorAction === "compile" ? "Prompt compilation failed" : errorAction === "launch" ? "Execution failed" : errorAction === "verify" ? "Verification could not be saved" : errorAction === "export" ? "Packet export failed" : "Workspace error"}</strong><span className="mt-1 block">{error}</span></div>{errorAction === "compile" && <button className="button-secondary shrink-0" type="button" onClick={() => void generate()}>Try again</button>}</div>}
    <div className="space-y-6"><section className="panel"><div className="border-b border-white/10 px-5 py-4"><p className="eyebrow">01 · Source of truth</p><h2 className="section-title">Project context</h2></div><div className="grid gap-0 divide-y divide-white/10 md:grid-cols-2 md:divide-x md:divide-y-0">{[["Project Scope & Goals", blueprint.architectureOverview], ["Target Audience & Use Cases", blueprint.coreLogic], ["Dependencies", blueprint.dependencies.join(", ") || "None specified"], ["Technical Constraints", (blueprint as any).technicalConstraints?.join(" · ") || "None specified"], ["Comments / Extra Context", blueprint.constraints.join(" · ") || "None specified"]].map(([label, value]) => <div className="p-5" key={label}><p className="meta-label">{label}</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-300">{value}</p></div>)}</div></section>
      {blueprint.implementationPlan && <section className="packet-panel panel"><div className="border-b border-white/10 px-5 py-4"><p className="eyebrow">Architecture packet</p><h2 className="section-title">The end goal, made reviewable</h2></div><div className="grid gap-6 p-5 lg:grid-cols-[1fr_1fr]"><div><p className="text-sm leading-6 text-slate-300">{blueprint.implementationPlan.summary}</p><p className="meta-label mt-6">Sequence</p><ol className="mt-3 space-y-3">{blueprint.implementationPlan.steps.map((step, index) => <li className="flex gap-3 text-sm text-slate-300" key={step}><span className="step-index">{String(index + 1).padStart(2, "0")}</span><span>{step}</span></li>)}</ol></div><div><p className="meta-label">Files to touch</p><div className="mt-3 space-y-2">{blueprint.implementationPlan.filesToTouch.map((file) => <div className="file-pill" key={file}>{file}</div>)}</div><p className="meta-label mt-6">Acceptance checklist</p><ul className="mt-3 space-y-2 text-sm text-slate-300">{blueprint.implementationPlan.acceptanceCriteria.map((criterion) => <li className="flex gap-2" key={criterion}><span className="check-mark">✓</span><span>{criterion}</span></li>)}</ul></div></div></section>}
      <PromptPreview prompt={prompt} /><ExecutionLauncher prompt={prompt} launching={launching} catalog={catalog} catalogLoading={catalogLoading} selection={creationSelection ?? { provider: "mock", model: "deterministic-local" }} selectionReady={Boolean(creationSelection)} onSelectionChange={setCreationSelection} onRefreshCatalog={onRefreshCatalog} onLaunch={() => void launch()} /><ExecutionResult execution={execution} onGenerateCoreDocs={handleGenerateCoreDocs} generatingCoreDocs={generatingCoreDocs} selectedCoreDocs={selectedCoreDocs} onCoreDocsChange={setSelectedCoreDocs} /><VerificationPanel execution={execution} saving={verifying} onVerify={verify} /><ExecutionTimeline executions={executions} />
    </div>
  </>;
}
