import { useEffect, useState } from "react";
import type { Blueprint, ExecutionRecord, PromptArtifact } from "@the-vault/shared";
import { api } from "../lib/api";
import { ExecutionTimeline } from "../components/ExecutionTimeline";
import { PromptPreview } from "../components/PromptPreview";

export function BlueprintDetail({ id, onNavigate }: { id: string; onNavigate: (path: string) => void }) {
  const [blueprint, setBlueprint] = useState<Blueprint>(); const [prompt, setPrompt] = useState<PromptArtifact>(); const [executions, setExecutions] = useState<ExecutionRecord[]>([]); const [loading, setLoading] = useState(true); const [generating, setGenerating] = useState(false); const [error, setError] = useState("");
  async function load() { try { const [nextBlueprint, nextExecutions] = await Promise.all([api.getBlueprint(id), api.getExecutions(id)]); setBlueprint(nextBlueprint); setExecutions(nextExecutions); try { setPrompt(await api.getPrompt(id)); } catch (promptError) { if (!(promptError instanceof Error && promptError.message === "Prompt artifact not found")) throw promptError; } } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Unable to load blueprint"); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [id]);
  async function generate() { setGenerating(true); setError(""); try { const result = await api.generatePrompt(id); setPrompt(result.promptArtifact); setExecutions((current) => [result.executionRecord, ...current]); } catch (generateError) { setError(generateError instanceof Error ? generateError.message : "Unable to generate prompt"); } finally { setGenerating(false); } }
  if (loading) return <div className="empty-panel"><div className="spinner" /><p>Loading blueprint…</p></div>;
  if (!blueprint) return <div className="alert-error">{error || "Blueprint not found"}</div>;
  return <><div className="mb-8"><button className="back-link" onClick={() => onNavigate("/dashboard")}>← Back to blueprints</button><div className="mt-8 flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><div className="flex items-center gap-3"><span className="tag">{blueprint.framework}</span><span className="text-xs text-slate-500">Updated {new Date(blueprint.updatedAt).toLocaleDateString()}</span></div><h1 className="page-title mt-4">{blueprint.name}</h1><p className="page-subtitle">{blueprint.description}</p></div><button className="button-primary" disabled={generating} onClick={() => void generate()}>{generating ? "Preparing…" : "Generate Codex prompt →"}</button></div></div>{error && <div className="alert-error mb-6">{error}</div>}<div className="grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><section className="panel"><div className="border-b border-white/10 px-5 py-4"><p className="eyebrow">Specification</p><h2 className="section-title">Architecture context</h2></div><div className="grid gap-0 divide-y divide-white/10 md:grid-cols-2 md:divide-x md:divide-y-0">{[["Target path", blueprint.targetPath], ["Language", blueprint.language], ["Architecture", blueprint.architectureOverview], ["Core logic", blueprint.coreLogic], ["Layout and UI", blueprint.layoutDesign], ["Dependencies", blueprint.dependencies.join(", ") || "None specified"], ["Constraints", blueprint.constraints.join(" · ") || "None specified"]].map(([label, value]) => <div className="p-5" key={label}><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-300">{value}</p></div>)}</div></section><div className="space-y-6"><PromptPreview prompt={prompt} /><ExecutionTimeline executions={executions} /></div></div></>;
}
