import type { Blueprint, ProviderStatus as ProviderStatusData } from "@the-vault/shared";
import { ProviderStatus } from "../components/ProviderStatus";

type DashboardProps = { blueprints: Blueprint[]; providerStatus?: ProviderStatusData; loading: boolean; error?: string; onNavigate: (path: string) => void };

export function Dashboard({ blueprints, providerStatus, loading, error, onNavigate }: DashboardProps) {
  return <>
    <section className="dashboard-hero mb-8"><div className="hero-grid" /><div className="relative flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><div className="mb-5 flex items-center gap-3"><span className="live-mark"><span />LOCAL WORKSPACE</span><ProviderStatus status={providerStatus} /></div><h1 className="page-title max-w-3xl">Architecture, with a<br /><span className="gradient-text">visible chain of custody.</span></h1><p className="page-subtitle max-w-2xl">Turn a human brief into a bounded blueprint, a reviewable AI handoff, and evidence you can trust.</p></div><button className="button-primary hero-button" onClick={() => onNavigate("/blueprints/new")}>Start with a brief <span>↗</span></button></div><div className="relative mt-10 grid gap-3 sm:grid-cols-3"><div className="metric-card"><span className="metric-value">{blueprints.length.toString().padStart(2, "0")}</span><span className="metric-label">Blueprints in vault</span></div><div className="metric-card"><span className="metric-value">{blueprints.filter((blueprint) => blueprint.implementationPlan).length.toString().padStart(2, "0")}</span><span className="metric-label">Architecture packets</span></div><div className="metric-card"><span className="metric-value text-emerald-300">{providerStatus?.available ? "ON" : "—"}</span><span className="metric-label">Local model signal</span></div></div></section>
    {error && <div className="mb-5 alert-error"><strong>Could not load the vault.</strong> {error}</div>}
    {loading ? <div className="empty-panel"><div className="spinner" /><p>Loading your architecture vault…</p></div> : blueprints.length === 0 ? <div className="empty-panel min-h-[360px] flex-col justify-center text-center"><span className="mb-5 grid h-14 w-14 place-items-center rounded-2xl bg-cyan-400/10 text-2xl text-cyan-300">✦</span><h2 className="text-xl font-semibold text-white">Your architecture vault is empty</h2><p className="mt-2 max-w-md text-sm text-slate-400">Start with a brief and let the local model shape the first reviewable blueprint.</p><button className="button-primary mt-6" onClick={() => onNavigate("/blueprints/new")}>Create your first blueprint</button></div> : <section><div className="mb-4 flex items-end justify-between"><div><p className="eyebrow">Your vault</p><h2 className="section-title text-xl">Recent blueprints</h2></div><span className="text-xs uppercase tracking-wider text-slate-600">Select a card to review</span></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{blueprints.map((blueprint) => <button className="panel card-hover blueprint-card text-left" key={blueprint.id} onClick={() => onNavigate(`/blueprints/${blueprint.id}`)}><div className="flex items-start justify-between gap-3"><span className="tag">{blueprint.framework}</span><span className="text-xs text-slate-500">{new Date(blueprint.updatedAt).toLocaleDateString()}</span></div><h2 className="mt-5 text-lg font-semibold text-white">{blueprint.name}</h2><p className="mt-2 line-clamp-3 text-sm leading-6 text-slate-400">{blueprint.description}</p><div className="mt-6 flex items-center justify-between text-xs text-slate-500"><span>{blueprint.language} · {blueprint.dependencies.length} dependencies</span><span className="card-arrow">↗</span></div>{blueprint.implementationPlan && <div className="mt-4 flex items-center gap-2 text-xs text-emerald-300"><span className="check-mark">✓</span> Architecture packet attached</div>}</button>)}</div></section>}
  </>;
}
